services:
  db:
    image: postgres:latest
    container_name: pizzeria-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pizzapass
      POSTGRES_DB: pizzeria
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer:latest
    container_name: pizzeria-adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8085:8080"

volumes:
  postgres_data:
